dep update + fixed win10/11 compatibility issue with app manifest file
System.InvalidOperationException: Unable to create child window for native control host. Application manifest with supported OS list might be required.